In [7]:
filename = "PatientCorePopulatedTable.csv"
values = []
with open(filename) as file:
    next(file)
    for line in file:
        if not line.strip():
            continue
        _, _, _, _, mstatus, _, poverty = line.strip().split(',')
        values.append((mstatus, poverty))

sorted(values, key=lambda x: (x[0], float(x[1])))

[('Divorced', '6.48'),
 ('Divorced', '11.08'),
 ('Divorced', '11.88'),
 ('Divorced', '14.07'),
 ('Divorced', '14.58'),
 ('Divorced', '18.17'),
 ('Divorced', '19.41'),
 ('Divorced', '19.49'),
 ('Divorced', '19.52'),
 ('Divorced', '83.75'),
 ('Divorced', '88.65'),
 ('Married', '3.3'),
 ('Married', '4.34'),
 ('Married', '4.51'),
 ('Married', '5.94'),
 ('Married', '6.67'),
 ('Married', '8.81'),
 ('Married', '9.1'),
 ('Married', '10.3'),
 ('Married', '10.35'),
 ('Married', '10.87'),
 ('Married', '11.25'),
 ('Married', '11.89'),
 ('Married', '12.01'),
 ('Married', '12.41'),
 ('Married', '12.8'),
 ('Married', '13.23'),
 ('Married', '13.9'),
 ('Married', '14.03'),
 ('Married', '14.15'),
 ('Married', '14.2'),
 ('Married', '14.81'),
 ('Married', '14.87'),
 ('Married', '15.04'),
 ('Married', '15.11'),
 ('Married', '15.31'),
 ('Married', '16.09'),
 ('Married', '16.71'),
 ('Married', '16.76'),
 ('Married', '17.72'),
 ('Married', '17.84'),
 ('Married', '18.05'),
 ('Married', '18.05'),
 ('Married', '18.08'),
 ('Married', '18.2'),
 ('Married', '18.33'),
 ('Married', '18.65'),
 ('Married', '18.8'),
 ('Married', '18.91'),
 ('Married', '19.22'),
 ('Married', '19.46'),
 ('Married', '19.5'),
 ('Married', '19.66'),
 ('Married', '19.74'),
 ('Married', '93.6'),
 ('Married', '94.06'),
 ('Separated', '10.8'),
 ('Separated', '13.03'),
 ('Separated', '17.98'),
 ('Separated', '19.36'),
 ('Separated', '98.4'),
 ('Single', '1.7'),
 ('Single', '7.59'),
 ('Single', '11.04'),
 ('Single', '11.15'),
 ('Single', '11.16'),
 ('Single', '11.43'),
 ('Single', '12.86'),
 ('Single', '12.92'),
 ('Single', '13.1'),
 ('Single', '13.97'),
 ('Single', '14.28'),
 ('Single', '14.49'),
 ('Single', '14.49'),
 ('Single', '14.9'),
 ('Single', '14.99'),
 ('Single', '15.24'),
 ('Single', '15.56'),
 ('Single', '15.72'),
 ('Single', '15.98'),
 ('Single', '16.24'),
 ('Single', '16.32'),
 ('Single', '16.43'),
 ('Single', '16.69'),
 ('Single', '16.86'),
 ('Single', '16.88'),
 ('Single', '18.36'),
 ('Single', '18.41'),
 ('Single', '18.88'),
 ('Single', '19.52'),
 ('Single', '89.44'),
 ('Single', '93.23'),
 ('Single', '94'),
 ('Unknown', '12.38'),
 ('Unknown', '15.02'),
 ('Unknown', '16.89'),
 ('Unknown', '18.95'),
 ('Unknown', '19.16'),
 ('Unknown', '82.08'),
 ('Widowed', '88.66')]

In [14]:
filename = "PatientCorePopulatedTable.csv"

sorted(
    [
        (line.strip().split(',')[4], float(line.strip().split(',')[6])) 
             for line in open(filename) if line and not line.startswith('Patient')
    ], 
    key=lambda x: (x[0], -x[1])
)

[('Divorced', 88.65),
 ('Divorced', 83.75),
 ('Divorced', 19.52),
 ('Divorced', 19.49),
 ('Divorced', 19.41),
 ('Divorced', 18.17),
 ('Divorced', 14.58),
 ('Divorced', 14.07),
 ('Divorced', 11.88),
 ('Divorced', 11.08),
 ('Divorced', 6.48),
 ('Married', 94.06),
 ('Married', 93.6),
 ('Married', 19.74),
 ('Married', 19.66),
 ('Married', 19.5),
 ('Married', 19.46),
 ('Married', 19.22),
 ('Married', 18.91),
 ('Married', 18.8),
 ('Married', 18.65),
 ('Married', 18.33),
 ('Married', 18.2),
 ('Married', 18.08),
 ('Married', 18.05),
 ('Married', 18.05),
 ('Married', 17.84),
 ('Married', 17.72),
 ('Married', 16.76),
 ('Married', 16.71),
 ('Married', 16.09),
 ('Married', 15.31),
 ('Married', 15.11),
 ('Married', 15.04),
 ('Married', 14.87),
 ('Married', 14.81),
 ('Married', 14.2),
 ('Married', 14.15),
 ('Married', 14.03),
 ('Married', 13.9),
 ('Married', 13.23),
 ('Married', 12.8),
 ('Married', 12.41),
 ('Married', 12.01),
 ('Married', 11.89),
 ('Married', 11.25),
 ('Married', 10.87),
 ('Married', 10.35),
 ('Married', 10.3),
 ('Married', 9.1),
 ('Married', 8.81),
 ('Married', 6.67),
 ('Married', 5.94),
 ('Married', 4.51),
 ('Married', 4.34),
 ('Married', 3.3),
 ('Separated', 98.4),
 ('Separated', 19.36),
 ('Separated', 17.98),
 ('Separated', 13.03),
 ('Separated', 10.8),
 ('Single', 94.0),
 ('Single', 93.23),
 ('Single', 89.44),
 ('Single', 19.52),
 ('Single', 18.88),
 ('Single', 18.41),
 ('Single', 18.36),
 ('Single', 16.88),
 ('Single', 16.86),
 ('Single', 16.69),
 ('Single', 16.43),
 ('Single', 16.32),
 ('Single', 16.24),
 ('Single', 15.98),
 ('Single', 15.72),
 ('Single', 15.56),
 ('Single', 15.24),
 ('Single', 14.99),
 ('Single', 14.9),
 ('Single', 14.49),
 ('Single', 14.49),
 ('Single', 14.28),
 ('Single', 13.97),
 ('Single', 13.1),
 ('Single', 12.92),
 ('Single', 12.86),
 ('Single', 11.43),
 ('Single', 11.16),
 ('Single', 11.15),
 ('Single', 11.04),
 ('Single', 7.59),
 ('Single', 1.7),
 ('Unknown', 82.08),
 ('Unknown', 19.16),
 ('Unknown', 18.95),
 ('Unknown', 16.89),
 ('Unknown', 15.02),
 ('Unknown', 12.38),
 ('Widowed', 88.66)]